// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD12cP3oyL5xaibzXsVspHIZcFxxOY_BJQ',
    appId: '1:645094028036:web:de17295a326dbdea90d651',
    messagingSenderId: '645094028036',
    projectId: 'chat-moaz',
    authDomain: 'chat-moaz.firebaseapp.com',
    storageBucket: 'chat-moaz.firebasestorage.app',
    measurementId: 'G-RW0D63WETM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_mXeXjwOz-KFFXdwYNf82lFAfkiqL78Y',
    appId: '1:645094028036:android:d1995b645d5acc7690d651',
    messagingSenderId: '645094028036',
    projectId: 'chat-moaz',
    storageBucket: 'chat-moaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkWAd05XDwnaFgvmHxzQBzdpqCEBAgO2k',
    appId: '1:645094028036:ios:198709ec2ab3ecb190d651',
    messagingSenderId: '645094028036',
    projectId: 'chat-moaz',
    storageBucket: 'chat-moaz.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkWAd05XDwnaFgvmHxzQBzdpqCEBAgO2k',
    appId: '1:645094028036:ios:198709ec2ab3ecb190d651',
    messagingSenderId: '645094028036',
    projectId: 'chat-moaz',
    storageBucket: 'chat-moaz.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD12cP3oyL5xaibzXsVspHIZcFxxOY_BJQ',
    appId: '1:645094028036:web:8ab44017e508417c90d651',
    messagingSenderId: '645094028036',
    projectId: 'chat-moaz',
    authDomain: 'chat-moaz.firebaseapp.com',
    storageBucket: 'chat-moaz.firebasestorage.app',
    measurementId: 'G-VRJN3KS0SD',
  );
}
